### PR TITLE
Create flag for negative equations

### PR DESCRIPTION
**Pull request by iulyaav**
When the argument for negative equations is not used, in case of negative subtractions the terms are interchanged

### CODE REVIEW

**Comment by jcandan** [comment]
Phenomenal! Though I don't see the need to string type the user response given input's return is a string. I am relatively new to Python, so if there's precedent, please let me know.

**Comment by iulyaav** [comment]
I did that because you were comparing a string of _correct_ with the user input, which didn't come in as a string, therefore when answering the equations you would have to write something like:

10 + 1 = "11"

in order to match as correct. I thought it might be extra effort to remember to add the quotes each time. But maybe there was a reason why you put it there and I meddled with it unnecessarily and if that's the case, sorry :")

**Comment by jcandan** [comment]
Oh, no worries. In this case, `correct` is an integer, which required that we convert it to a string to compare with the returned string from `user_response`. Though, you're saying `user_input` is not coming in as a string for you, is that correct?

**Comment by iulyaav** [comment]
Oh.... Ohhh... You were right.
Usually I use the alias 'python' for python3, yet on my home laptop python = python2, but I had forgotten that. In python 2, writing the number 2 on a console will write it as an int, while in python 3 anything you write on a console comes as a string. I made a mistake there.

**Comment by iulyaav** [comment]
I removed the unnecessary cast

**Comment by jcandan** [comment]
Awesome, I did find a strange behavior though. Somehow, this swap is causing `term_1` to always be 10. Run the following with your changes to see it.

```
python math_quiz.py -s1 2 -e1 2 -sn
python math_quiz.py -s1 2 -e1 2 -s
```

**Comment by jcandan** [comment]
Wow, okay, this would be a tough find. Essentially, during the `for...in` loop, we're immediately changing the value of `term_1` to the last element, and that remains the value of `term_1` in the remainder of the loop. 

```
for term_1 in terms_1:
    for term_2 in terms_2:
        term_1 = 5
```

I think the fix might be to always assign `tmp_1, tmp 2 = term_1, term_2` and use these tmp variables in the appended questions dict. And, if negative, swap them with `tmp_2, tmp1 = term_1, term_2`

**Comment by iulyaav** [comment]
Wow, that is indeed a tough find. We could do that. Or we might just switch them back on after appending to the dictionary? It might save some space. Although, in this context, it's negligible.

**Comment by jcandan** [comment]
Good call. I leave it to you, whichever you think is both efficient and clear.

**Comment by jcandan** [comment]
I went ahead with a comparison of the two options.

### uses a tmp variable
```

tmp_1, tmp_2 = term_1, term_2
if not args.negative and method == 'sub' and term_2 > term_1:
    tmp_1, tmp_2 = term_2, term_1
questions.append({'first': tmp_1, 'second': tmp_2, 'method': method, 'symbol': symbol})
```

### switches back the swapped terms after append

```
# store switched outside the loop
switched = False
. . .
if not args.negative and method == 'sub' and term_2 > term_1:
    term_1, term_2 = term_2, term_1
    switched = True
questions.append({'first': term_1, 'second': term_2, 'method': method, 'symbol': symbol})
if switched:
    term_1, term_2 = term_2, term_1
    switched = False
```

Between the two, it really seems much cleaner to use a tmp variable. I'll commit this and merge your PR.

**Comment by iulyaav** [comment]
Ok. You're right, it looks so much cleaner.

**Comment by jcandan** [comment]
Would you like to fix it? Or, if you enabled **Allow edits from maintainers**, I can push a fix to your PR.

**Comment by iulyaav** [comment]
May I fix it, please? ^.^ I'll leave my work in about an hour, so around then.

**Comment by jcandan** [comment]
Of course! I've been debating leaving that note hoping you might experiment with it yourself. But last night my daughter was going through her practice with it on your unmerged local copy, and I thought this morning I might poke and get this moving along. Thank you very much, by the way. Excellent job.

**Pull request merged**
